FROM node:lts as builder
WORKDIR /app/


COPY webui webui
WORKDIR /app/webui
RUN npm run build-prod

# Stage 2: Serve the application from Nginx
FROM nginx:stable
COPY --from=builder /app/webui/dist /usr/share/nginx/html

#should be already in the container but just to make sure
EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]