# Start from the latest Golang base image
FROM golang:latest

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN go build -o webapi ./cmd/webapi/

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run the executable
CMD ["./webapi"]